### ISSUE TITLE
英文无法朗读？

### ISSUE THREAD

**Issue by Pantyhose-X** [soui3-demo/sinstar3#1]
主要用来学习语言。
这样可以纠正发音和加深记忆。

win10系统
输入法中文可以朗读、英文无法朗读？
如果你们可以把朗读功能独立出来更好、不管输入什么语言都朗读、监听微软输入法、、

**Comment by setoutsoft** [comment]
英文朗读要开另一种模式。自己好好看说明。启程输入法是一个输入法，不是朗读工具，不支持朗读其它输入法。
