### ISSUE TITLE
请帮忙导出个词库格式码表

### ISSUE THREAD

**Issue by wwzrh** [soui3-demo/sinstar3#2]
10笔字根GBK.cit，这个是启程2.x词库格式，在启程3.x不能打开使用，请帮忙导出码表，重新编辑使用。
@setoutsoft @bugHappy @LittleKu @cnsheds
[10笔字根GBK.zip](https://github.com/soui3-demo/sinstar3/files/11025174/10.GBK.zip)

**Comment by setoutsoft** [comment]
自己下载一个启程2.x，用里面的工具导出文本，再转换成3.x

**Comment by wwzrh** [comment]
启程2.x词库管理程序禁止编码导出，希望能在启程3.x使用，请帮忙导出这个码表

@setoutsoft @bugHappy @LittleKu @cnsheds

**Comment by setoutsoft** [comment]
禁止导出的话，我也没有办法。
