### ISSUE TITLE
开源协议是什么？

### ISSUE THREAD

**Issue by GlocKieHuan** [soui3-demo/sinstar3#3]
支持商用吗？

**Comment by setoutsoft** [comment]
核心算法不开源。输入法接口及界面代码是开源的。只供借鉴，不支持二次开发，二次发布。

**Comment by GlocKieHuan** [comment]
想请教一下，在win7系统上怎么获取当前输入法的名称呢？win10可以通过TSF的Get Activate Language Profile()接口，win7返回的是默认输入法名称

**Comment by setoutsoft** [comment]
很久不做输入法了，自己看代码吧。
